- name: Cache update
  ansible.legacy.apt:
    update_cache: true
- name: Installing nginx
  ansible.legacy.apt:
    name: nginx
    state: present
  notify:
    - Start_nginx
- name: Allow
  community.general.ufw:
    rule: allow
    port: '80'
    proto: tcp
- name: Copy nginx conf
  ansible.builtin.copy:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: "0644"
  notify:
    - Reload_nginx
