- name: Install nginx both OS
  include_tasks: tasks/ubuntu_tasks.yml
  when: ansible_distribution == 'Ubuntu'

#  - ansible.builtin.debug:
#     msg: Ubuntu started


- name: Isntall nginx
  include_tasks: tasks/centos_tasks.yml
  when: ansible_distribution == 'CentOS'


    #  - ansible.builtin.debug:
    # msg: Centos started
