- name: Cache update
  ansible.legacy.apt:
    update_cache: true

- name: Installing nginx
  ansible.legacy.apt:
    name: "{{ web_server }}"
    state: present
  when: ansible_distribution == 'Ubuntu'
  notify:
    - Start_nginx

- name: Task Ubuntu
  debug:
    msg: "Runing on Ubuntu"


- name: Check Nginx configuration
  command: nginx -t
  changed_when: false
  register: nginx_config_check

- name: Reload Nginx configuration
  command: nginx -s reload
  when: nginx_config_check.stdout.find('successful') != -1
  notify:
    - Restart_nginx

- name: Port Open Ubuntu
  ufw:
    rule: allow
    port: 80
    proto: tcp
  when: ansible_distribution == 'Ubuntu'

- name: copy
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    Reload_nginx
