- name: Install nginx
  hosts: localhost
  become: true
  vars:
  tasks:
    - name: Cache update
      ansible.legacy.apt:
        update_cache: true
    - name: Installing nginx
      ansible.legacy.apt:
        name: nginx
        state: present
      notify:
        Start_nginx
    - name: Allow
      community.general.ufw:
        rule: allow
        port: '80'
        proto: tcp
    - name: Copy nginx file
      ansible.builtin.copy:
        src: ./index.html
        dest: /var/www/html
        mode: "0644"
      notify:
        - Reload_nginx
  handlers:
  - name: Reload_nginx
    ansible.builtin.service:
      name: nginx
      state: reloaded
  - name: Start_nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: true
