- name: Install nginx
  hosts: localhost
  become: true
  vars:
  tasks:
    - name: Cache update
      ansible.legacy.apt:
        update_cache: true
    - name: Installing nginx
      ansible.legacy.apt:
        name: nginx
        state: present
    - name: Start service
      ansible.legacy.service:
        name: nginx
        state: started
        enabled: true
    - name: Allow
      community.general.ufw:
        rule: allow
        port: '80'
        proto: tcp
    - name: Copy nginx file
      copy:
        src: ./index.html
        dest: /etc/nginx/nginx.conf
        mode: 0644
      notify: 
        - reload_nginx
  handlers:
  - name: reload_nginx
    service:
      name: nginx
      state: reload

